# 网站信息
site_name: Alexander's Notebook
site_description: 我的个人学习笔记 - 数学、物理、编程
site_author: Alexander James Carter
site_url: https://notebook.alexander.xin

# 版权信息
copyright: '&copy; 2025 <a href="https://alexander.xin" target="_blank" rel="noopener">Alexander James Carter</a>'

# 额外配置
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/alexander-xin
          name: GitHub
        - icon: fontawesome/solid/envelope
          link: mailto:notebook@alexander.xin
          name: 邮箱联系
        - icon: fontawesome/solid/home
          link: https://alexander.xin
          name: 个人主页

    # 生成器信息
    generator: false
# 仓库信息（可选）
repo_name: AlexanderJ-Carter/Notebook
repo_url: https://github.com/AlexanderJ-Carter/Notebook
edit_uri: edit/master/docs/

# 主题配置
theme:
    name: material
    language: zh
    palette:
        # 浅色模式 - 蓝色调
        - media: '(prefers-color-scheme: light)'
          scheme: default
          primary: blue
          accent: light blue
          toggle:
              icon: material/brightness-7
              name: 切换到暗色模式
        # 深色模式 - 蓝色调
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          primary: blue
          accent: light blue
          toggle:
              icon: material/brightness-4
              name: 切换到浅色模式

    # 功能特性
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.path
        - navigation.top
        - search.highlight
        - search.share
        - search.suggest
        - content.code.copy
        - content.code.annotate
        - content.tabs.link

    # 图标和字体
    icon:
        repo: fontawesome/brands/github
    font:
        text: Roboto
        code: Roboto Mono

# GitHub Pages 配置
use_directory_urls: true

# 插件
plugins:
    - search:
          lang:
              - zh
              - en
    - tags
    - git-revision-date-localized:
          enable_creation_date: true
          fallback_to_build_date: true

# Markdown 扩展
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - attr_list
    - md_in_html
    - tables
    - footnotes
    - pymdownx.arithmatex:
          generic: true

# 数学公式支持和评论系统
extra_javascript:
    - javascripts/mathjax.js
    - javascripts/giscus.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# 自定义样式
extra_css:
    - stylesheets/extra.css

# 导航结构
nav:
    - 首页: index.md
    - 数理知识:
          - 概述: mathematics/index.md
    - 编程基础:
          - 概述: programming/index.md
    - 实用工具:
          - 概述: tools/index.md
    - 学习心得:
          - 概述: learning/index.md
    - 项目实践:
          - 概述: projects/index.md
    - 关于: about.md
